title: Serial Device Emulator
description: Scriptable COM Port Data Emulator Built with C#
show_downloads: true
google_adsense: ca-pub-1135979461412092
google_analytics: G-MKQK789F6L
theme: jekyll-theme-cayman

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-commonmark-ghpages

whitelist:
  - jekyll-commonmark-ghpages

github:
  private: true
